version: '3.8'

services:
    app:
        user: "www"
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: my-laravel-app
        restart: unless-stopped
        volumes:
            - ./:/var/www
            - ./.env:/var/www/.env
        networks:
            - app-network
        depends_on:
            - database
    nginx:
        image: nginx:alpine
        container_name: laravel-nginx
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - app
        networks:
            - app-network

    node:
        build:
            context: .
            dockerfile: Dockerfile.node
        image: laravel-node
        container_name: laravel-node
        ports:
            - "3000:3000"
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - /var/www/node_modules
        networks:
            - app-network

    database:
        image: postgres:15.0
        restart: unless-stopped
        ports:
            - "5433:5432"
        environment:
            POSTGRES_DB: ${DB_DATABASE?}
            POSTGRES_USER: ${DB_USERNAME?}
            POSTGRES_PASSWORD: ${DB_PASSWORD?}
        container_name: database
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
